/*
 * 7429a0 IRQ header file autogenerated by update_bchp.pl
 * DO NOT EDIT THIS FILE BY HAND.
 *
 * Copyright (C) 2011 Broadcom Corporation
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 */

#ifndef _BRCMIRQ_H_
#define _BRCMIRQ_H_

#define BRCM_IRQ_EHCI0_0	56
#define BRCM_IRQ_EHCI0_1	57
#define BRCM_IRQ_EHCI1_0	61
#define BRCM_IRQ_EHCI1_1	62
#define BRCM_IRQ_GENET_0_A	16
#define BRCM_IRQ_GENET_0_B	17
#define BRCM_IRQ_GENET_1_A	18
#define BRCM_IRQ_GENET_1_B	19
#define BRCM_IRQ_HIF		23
#define BRCM_IRQ_HIF_SPI	24
#define BRCM_IRQ_MOCA		28
#define BRCM_IRQ_OHCI0_0	58
#define BRCM_IRQ_OHCI0_1	59
#define BRCM_IRQ_OHCI1_0	63
#define BRCM_IRQ_OHCI1_1	64
#define BRCM_IRQ_SATA		33
#define BRCM_IRQ_SDIO0		35
#define BRCM_IRQ_SDIO1		36
#define BRCM_IRQ_STANDBY	41
#define BRCM_IRQ_UARTA		52
#define BRCM_IRQ_UARTB		53
#define BRCM_IRQ_UARTC		54
#define BRCM_IRQLIST_EHCI	{ 56, 57, 61, 62 }
#define BRCM_IRQLIST_OHCI	{ 58, 59, 63, 64 }

#endif /* _BRCMIRQ_H_ */
