/***************************************************************************
 *     Copyright (c) 1999-2012, Broadcom Corporation
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on         Sat Jun 16 03:07:39 2012
 *                 MD5 Checksum         d41d8cd98f00b204e9800998ecf8427e
 *
 * Compiled with:  RDB Utility          combo_header.pl
 *                 RDB Parser           3.0
 *                 unknown              unknown
 *                 Perl Interpreter     5.008005
 *                 Operating System     linux
 *
 * Revision History:
 *
 * $brcm_Log: $
 *
 ***************************************************************************/

#ifndef BCHP_EBI_H__
#define BCHP_EBI_H__

/***************************************************************************
 *EBI - EBI Registers
 ***************************************************************************/
#define BCHP_EBI_CS_BASE_0                       0x00410c00 /* EBI CS Base 0 Register */
#define BCHP_EBI_CS_BASE_1                       0x00410c08 /* EBI CS Base 1 Register */
#define BCHP_EBI_CS_SPI_SELECT                   0x00410d20 /* SPI CS Select */

/***************************************************************************
 *CS_BASE_0 - EBI CS Base 0 Register
 ***************************************************************************/
/* EBI :: CS_BASE_0 :: base_addr [31:13] */
#define BCHP_EBI_CS_BASE_0_base_addr_MASK                          0xffffe000
#define BCHP_EBI_CS_BASE_0_base_addr_SHIFT                         13

/* EBI :: CS_BASE_0 :: reserved0 [12:04] */
#define BCHP_EBI_CS_BASE_0_reserved0_MASK                          0x00001ff0
#define BCHP_EBI_CS_BASE_0_reserved0_SHIFT                         4

/* EBI :: CS_BASE_0 :: size [03:00] */
#define BCHP_EBI_CS_BASE_0_size_MASK                               0x0000000f
#define BCHP_EBI_CS_BASE_0_size_SHIFT                              0
#define BCHP_EBI_CS_BASE_0_size_SIZE_8KB                           0
#define BCHP_EBI_CS_BASE_0_size_SIZE_16KB                          1
#define BCHP_EBI_CS_BASE_0_size_SIZE_32KB                          2
#define BCHP_EBI_CS_BASE_0_size_SIZE_64KB                          3
#define BCHP_EBI_CS_BASE_0_size_SIZE_128KB                         4
#define BCHP_EBI_CS_BASE_0_size_SIZE_256KB                         5
#define BCHP_EBI_CS_BASE_0_size_SIZE_512KB                         6
#define BCHP_EBI_CS_BASE_0_size_SIZE_1MB                           7
#define BCHP_EBI_CS_BASE_0_size_SIZE_2MB                           8
#define BCHP_EBI_CS_BASE_0_size_SIZE_4MB                           9
#define BCHP_EBI_CS_BASE_0_size_SIZE_8MB                           10
#define BCHP_EBI_CS_BASE_0_size_SIZE_16MB                          11
#define BCHP_EBI_CS_BASE_0_size_SIZE_32MB                          12
#define BCHP_EBI_CS_BASE_0_size_SIZE_64MB                          13
#define BCHP_EBI_CS_BASE_0_size_SIZE_128MB                         14
#define BCHP_EBI_CS_BASE_0_size_SIZE_256MB                         15

/***************************************************************************
 *CS_BASE_1 - EBI CS Base 1 Register
 ***************************************************************************/
/* EBI :: CS_BASE_1 :: base_addr [31:13] */
#define BCHP_EBI_CS_BASE_1_base_addr_MASK                          0xffffe000
#define BCHP_EBI_CS_BASE_1_base_addr_SHIFT                         13
#define BCHP_EBI_CS_BASE_1_base_addr_DEFAULT                       0x00000000

/* EBI :: CS_BASE_1 :: reserved0 [12:04] */
#define BCHP_EBI_CS_BASE_1_reserved0_MASK                          0x00001ff0
#define BCHP_EBI_CS_BASE_1_reserved0_SHIFT                         4

/* EBI :: CS_BASE_1 :: size [03:00] */
#define BCHP_EBI_CS_BASE_1_size_MASK                               0x0000000f
#define BCHP_EBI_CS_BASE_1_size_SHIFT                              0
#define BCHP_EBI_CS_BASE_1_size_DEFAULT                            0x00000000
#define BCHP_EBI_CS_BASE_1_size_SIZE_8KB                           0
#define BCHP_EBI_CS_BASE_1_size_SIZE_16KB                          1
#define BCHP_EBI_CS_BASE_1_size_SIZE_32KB                          2
#define BCHP_EBI_CS_BASE_1_size_SIZE_64KB                          3
#define BCHP_EBI_CS_BASE_1_size_SIZE_128KB                         4
#define BCHP_EBI_CS_BASE_1_size_SIZE_256KB                         5
#define BCHP_EBI_CS_BASE_1_size_SIZE_512KB                         6
#define BCHP_EBI_CS_BASE_1_size_SIZE_1MB                           7
#define BCHP_EBI_CS_BASE_1_size_SIZE_2MB                           8
#define BCHP_EBI_CS_BASE_1_size_SIZE_4MB                           9
#define BCHP_EBI_CS_BASE_1_size_SIZE_8MB                           10
#define BCHP_EBI_CS_BASE_1_size_SIZE_16MB                          11
#define BCHP_EBI_CS_BASE_1_size_SIZE_32MB                          12
#define BCHP_EBI_CS_BASE_1_size_SIZE_64MB                          13
#define BCHP_EBI_CS_BASE_1_size_SIZE_128MB                         14
#define BCHP_EBI_CS_BASE_1_size_SIZE_256MB                         15

/***************************************************************************
 *CS_SPI_SELECT - SPI CS Select
 ***************************************************************************/
/* EBI :: CS_SPI_SELECT :: reserved0 [31:16] */
#define BCHP_EBI_CS_SPI_SELECT_reserved0_MASK                      0xffff0000
#define BCHP_EBI_CS_SPI_SELECT_reserved0_SHIFT                     16

/* EBI :: CS_SPI_SELECT :: EBI_CS_7_USES_SPI [15:15] */
#define BCHP_EBI_CS_SPI_SELECT_EBI_CS_7_USES_SPI_MASK              0x00008000
#define BCHP_EBI_CS_SPI_SELECT_EBI_CS_7_USES_SPI_SHIFT             15
#define BCHP_EBI_CS_SPI_SELECT_EBI_CS_7_USES_SPI_DEFAULT           0x00000000

/* EBI :: CS_SPI_SELECT :: EBI_CS_6_USES_SPI [14:14] */
#define BCHP_EBI_CS_SPI_SELECT_EBI_CS_6_USES_SPI_MASK              0x00004000
#define BCHP_EBI_CS_SPI_SELECT_EBI_CS_6_USES_SPI_SHIFT             14
#define BCHP_EBI_CS_SPI_SELECT_EBI_CS_6_USES_SPI_DEFAULT           0x00000000

/* EBI :: CS_SPI_SELECT :: EBI_CS_5_USES_SPI [13:13] */
#define BCHP_EBI_CS_SPI_SELECT_EBI_CS_5_USES_SPI_MASK              0x00002000
#define BCHP_EBI_CS_SPI_SELECT_EBI_CS_5_USES_SPI_SHIFT             13
#define BCHP_EBI_CS_SPI_SELECT_EBI_CS_5_USES_SPI_DEFAULT           0x00000000

/* EBI :: CS_SPI_SELECT :: EBI_CS_4_USES_SPI [12:12] */
#define BCHP_EBI_CS_SPI_SELECT_EBI_CS_4_USES_SPI_MASK              0x00001000
#define BCHP_EBI_CS_SPI_SELECT_EBI_CS_4_USES_SPI_SHIFT             12
#define BCHP_EBI_CS_SPI_SELECT_EBI_CS_4_USES_SPI_DEFAULT           0x00000000

/* EBI :: CS_SPI_SELECT :: EBI_CS_3_USES_SPI [11:11] */
#define BCHP_EBI_CS_SPI_SELECT_EBI_CS_3_USES_SPI_MASK              0x00000800
#define BCHP_EBI_CS_SPI_SELECT_EBI_CS_3_USES_SPI_SHIFT             11
#define BCHP_EBI_CS_SPI_SELECT_EBI_CS_3_USES_SPI_DEFAULT           0x00000000

/* EBI :: CS_SPI_SELECT :: EBI_CS_2_USES_SPI [10:10] */
#define BCHP_EBI_CS_SPI_SELECT_EBI_CS_2_USES_SPI_MASK              0x00000400
#define BCHP_EBI_CS_SPI_SELECT_EBI_CS_2_USES_SPI_SHIFT             10
#define BCHP_EBI_CS_SPI_SELECT_EBI_CS_2_USES_SPI_DEFAULT           0x00000000

/* EBI :: CS_SPI_SELECT :: EBI_CS_1_USES_SPI [09:09] */
#define BCHP_EBI_CS_SPI_SELECT_EBI_CS_1_USES_SPI_MASK              0x00000200
#define BCHP_EBI_CS_SPI_SELECT_EBI_CS_1_USES_SPI_SHIFT             9
#define BCHP_EBI_CS_SPI_SELECT_EBI_CS_1_USES_SPI_DEFAULT           0x00000000

/* EBI :: CS_SPI_SELECT :: EBI_CS_0_USES_SPI [08:08] */
#define BCHP_EBI_CS_SPI_SELECT_EBI_CS_0_USES_SPI_MASK              0x00000100
#define BCHP_EBI_CS_SPI_SELECT_EBI_CS_0_USES_SPI_SHIFT             8

/* EBI :: CS_SPI_SELECT :: SPI_EBI_CS_7_SEL [07:07] */
#define BCHP_EBI_CS_SPI_SELECT_SPI_EBI_CS_7_SEL_MASK               0x00000080
#define BCHP_EBI_CS_SPI_SELECT_SPI_EBI_CS_7_SEL_SHIFT              7
#define BCHP_EBI_CS_SPI_SELECT_SPI_EBI_CS_7_SEL_DEFAULT            0x00000000

/* EBI :: CS_SPI_SELECT :: SPI_EBI_CS_6_SEL [06:06] */
#define BCHP_EBI_CS_SPI_SELECT_SPI_EBI_CS_6_SEL_MASK               0x00000040
#define BCHP_EBI_CS_SPI_SELECT_SPI_EBI_CS_6_SEL_SHIFT              6
#define BCHP_EBI_CS_SPI_SELECT_SPI_EBI_CS_6_SEL_DEFAULT            0x00000000

/* EBI :: CS_SPI_SELECT :: SPI_EBI_CS_5_SEL [05:05] */
#define BCHP_EBI_CS_SPI_SELECT_SPI_EBI_CS_5_SEL_MASK               0x00000020
#define BCHP_EBI_CS_SPI_SELECT_SPI_EBI_CS_5_SEL_SHIFT              5
#define BCHP_EBI_CS_SPI_SELECT_SPI_EBI_CS_5_SEL_DEFAULT            0x00000000

/* EBI :: CS_SPI_SELECT :: SPI_EBI_CS_4_SEL [04:04] */
#define BCHP_EBI_CS_SPI_SELECT_SPI_EBI_CS_4_SEL_MASK               0x00000010
#define BCHP_EBI_CS_SPI_SELECT_SPI_EBI_CS_4_SEL_SHIFT              4
#define BCHP_EBI_CS_SPI_SELECT_SPI_EBI_CS_4_SEL_DEFAULT            0x00000000

/* EBI :: CS_SPI_SELECT :: SPI_EBI_CS_3_SEL [03:03] */
#define BCHP_EBI_CS_SPI_SELECT_SPI_EBI_CS_3_SEL_MASK               0x00000008
#define BCHP_EBI_CS_SPI_SELECT_SPI_EBI_CS_3_SEL_SHIFT              3
#define BCHP_EBI_CS_SPI_SELECT_SPI_EBI_CS_3_SEL_DEFAULT            0x00000000

/* EBI :: CS_SPI_SELECT :: SPI_EBI_CS_2_SEL [02:02] */
#define BCHP_EBI_CS_SPI_SELECT_SPI_EBI_CS_2_SEL_MASK               0x00000004
#define BCHP_EBI_CS_SPI_SELECT_SPI_EBI_CS_2_SEL_SHIFT              2
#define BCHP_EBI_CS_SPI_SELECT_SPI_EBI_CS_2_SEL_DEFAULT            0x00000000

/* EBI :: CS_SPI_SELECT :: SPI_EBI_CS_1_SEL [01:01] */
#define BCHP_EBI_CS_SPI_SELECT_SPI_EBI_CS_1_SEL_MASK               0x00000002
#define BCHP_EBI_CS_SPI_SELECT_SPI_EBI_CS_1_SEL_SHIFT              1
#define BCHP_EBI_CS_SPI_SELECT_SPI_EBI_CS_1_SEL_DEFAULT            0x00000000

/* EBI :: CS_SPI_SELECT :: SPI_EBI_CS_0_SEL [00:00] */
#define BCHP_EBI_CS_SPI_SELECT_SPI_EBI_CS_0_SEL_MASK               0x00000001
#define BCHP_EBI_CS_SPI_SELECT_SPI_EBI_CS_0_SEL_SHIFT              0

#endif /* #ifndef BCHP_EBI_H__ */

/* End of File */
