#!/bin/sh

export PATH=/bin:/sbin:/usr/bin:/usr/sbin:.

mount -t devpts none /dev/pts
mount -t proc none /proc
mount -t sysfs none /sys
mount -t tmpfs none /dev/shm

[ -e /sys/class/net/eth0 ] && udhcpc -i eth0
exec "$@"
